import {POSE_IDS,POSE_LABELS} from './poses.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {disposeGroup} from './human.js';
import {newProfile,switchProfile,validateComparison} from './profiles.js';
import {COMPOSITION_MODEL,compositionHint,toMorphParams,fromLegacyParams,bodyExample} from './composition.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
window.somaStartup?.loaded?.();
let state=newProfile('male');const profiles={};
let data,renderer,camera,controls,scenes=[],models=[],busy=false,ready=false,scheduled=false,anatomy,worker,pending=false,waiters=[],workerTimer;
const status=t=>$('#status').textContent=t;
const textureCache=new Map();
function assetTexture(path){if(!textureCache.has(path)){let done,failed;const loaded=new Promise((resolve,reject)=>{done=resolve;failed=reject;});const texture=new THREE.TextureLoader().load(path,()=>{done();render();},undefined,()=>failed(Error('人物外观贴图读取失败：'+path)));texture.colorSpace=THREE.SRGBColorSpace;texture.userData.loaded=loaded;textureCache.set(path,texture);}return textureCache.get(path);}
function withTimeout(promise,ms,message){let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(message)),ms);})]).finally(()=>clearTimeout(timer));}
function download(content,name,type){const blob=content instanceof Blob?content:new Blob([content],{type});const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function setupScene(){const scene=new THREE.Scene();scene.add(new THREE.HemisphereLight('#f3fcf7','#6b7777',2.2));const key=new THREE.DirectionalLight('#fff5e8',3.4);key.position.set(-2.5,4,3.5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-1.5;key.shadow.camera.right=1.5;key.shadow.camera.top=3;key.shadow.camera.bottom=-1;key.shadow.bias=-.0004;scene.add(key);const rim=new THREE.DirectionalLight('#d7e8ff',2);rim.position.set(2,2,-2);scene.add(rim);const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.24}));floor.rotation.x=-Math.PI/2;floor.position.y=-.008;floor.receiveShadow=true;scene.add(floor);const ring=new THREE.Mesh(new THREE.RingGeometry(.45,.455,96),new THREE.MeshBasicMaterial({color:'#697d79',transparent:true,opacity:.32,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=-.005;scene.add(ring);return scene;}
function resize(){if(!renderer)return;const host=$('#canvasHost'),w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);const count=state.triple?3:2;const aspect=w/count/h;const frustum=Math.max(2.18,.85/aspect);camera.left=-frustum*aspect/2;camera.right=frustum*aspect/2;camera.top=frustum/2;camera.bottom=-frustum/2;camera.updateProjectionMatrix();render();}
function render(){if(!renderer||!scenes.length)return;const size=renderer.getSize(new THREE.Vector2()),w=size.x,h=size.y,n=scenes.length;renderer.setScissorTest(true);for(let i=0;i<n;i++){const left=Math.floor(w*i/n),right=Math.floor(w*(i+1)/n);renderer.setViewport(left,0,right-left,h);renderer.setScissor(left,0,right-left,h);renderer.render(scenes[i],camera);}renderer.setScissorTest(false);}
function markAngle(isSelected){$$('[data-angle]').forEach(b=>{const on=isSelected(b);b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});}
function syncAngle(){const d=camera.position.clone().sub(controls.target),angle=Math.atan2(d.x,d.z)*180/Math.PI,level=Math.abs(Math.atan2(d.y,Math.hypot(d.x,d.z))*180/Math.PI)<.5;markAngle(b=>level&&Math.abs(((angle-Number(b.dataset.angle)+540)%360)-180)<.5);}
function setAngle(deg){const target=controls.target,dist=camera.position.distanceTo(target),r=deg*Math.PI/180;camera.position.set(target.x+Math.sin(r)*dist,target.y,target.z+Math.cos(r)*dist);camera.lookAt(target);controls.update();render();syncAngle();}
function reflect(){const p=state[state.edit];$$('[data-body-example]').forEach(b=>{const example=bodyExample(state.sex,p.height,b.dataset.bodyExample),on=Math.abs(p.bodyFatPercent-example.bodyFatPercent)<.001&&Math.abs(p.skeletalMuscleKg-example.skeletalMuscleKg)<.001;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});for(const [id,key,unit] of [['height','height','cm'],['fat','bodyFatPercent','%'],['muscle','skeletalMuscleKg','kg']]){$('#'+id).value=p[key];const value=(key==='height'?p[key]:p[key].toFixed(1))+' '+unit;$('#'+id+'Value').textContent=value;$('#'+id).setAttribute('aria-valuetext',value);}$('#compositionHint').textContent=compositionHint(state.sex,p);
 $$('[data-color]').forEach(b=>{b.disabled=state.garment==='blouse';b.title=state.garment==='blouse'?'配套衬衫保留原面料颜色':'';});$('#sex').value=state.sex;$('#bottom').value=state.bottom;$('#shoeStyle').value=state.shoeStyle;$('#stockings').checked=state.stockings;$('#showHair').checked=state.hair;$('#footwear').checked=state.footwear;$('#garment').value=state.garment;$('#wireframe').checked=state.wireframe;$('#bodyGhost').checked=state.ghost;
 for(const field of ['edit','fit','pose','color'])$$('[data-'+field+']').forEach(b=>{const selected=b.dataset[field]===state[field];b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});
 const delta=k=>{const d=Math.round((state.B[k]-state.A[k])*10)/10;return(d>0?'+':'')+d.toFixed(1);};$('#deltaHeight').innerHTML=delta('height')+' <small>cm</small>';$('#deltaFat').innerHTML=delta('bodyFatPercent')+' <small>百分点</small>';$('#deltaMuscle').innerHTML=delta('skeletalMuscleKg')+' <small>kg</small>';
 $('#compareMode').textContent=state.triple?'返回 A/B 对照':'比较三种版型';$('#syncStatus').textContent=state.triple?'同一 B 体型 · 三种版型':'相机 · 尺度 · 光照同步';
 const labels=state.triple?[['1','紧身','同一 B 体型'],['2','常规','同一 B 体型'],['3','宽松','同一 B 体型']]:[['A','基线体型','作为对照保留'],['B','模拟体型','由你调整']];
 $('#viewLabels').style.gridTemplateColumns=`repeat(${labels.length},1fr)`;$('#viewLabels').innerHTML=labels.map(([id,title,sub],i)=>`<div><b class="${i?'accent':''}">${id}</b><span>${title}<small>${sub}</small></span></div>`).join('');
}
function setExportDisabled(disabled){$$('#save,#capture,#exportGLB').forEach(b=>b.disabled=disabled);}
function failModel(error){clearTimeout(workerTimer);ready=false;busy=false;pending=false;worker?.terminate();waiters.splice(0).forEach(r=>r());window.somaStartup.fail(error);}
function runWorker(){clearTimeout(workerTimer);workerTimer=setTimeout(()=>failModel(Error('人体计算超过 30 秒，请重新载入。')),30000);busy=true;pending=false;setExportDisabled(true);status('正在重新适配人体与衣物…');worker.postMessage({type:'build',state});}
function update(){if(!ready)return Promise.resolve();reflect();const promise=new Promise(resolve=>waiters.push(resolve));if(busy)pending=true;else runWorker();return promise;}
function receiveGeometry(event){const result=event.data;if(result.type==='ready')return;clearTimeout(workerTimer);if(pending){runWorker();return;}if(result.type==='error'){failModel(Error('人体计算失败：'+result.message));return;}
 for(const scene of scenes)disposeGroup(scene);
 models=result.models.map(record=>{const group=new THREE.Group();group.name=record.name;group.userData=record.userData;for(const mesh of record.meshes){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(mesh.positions,3));g.setAttribute('normal',new THREE.BufferAttribute(mesh.normals,3));g.setIndex(new THREE.BufferAttribute(mesh.indices,1));if(mesh.uv)g.setAttribute('uv',new THREE.BufferAttribute(mesh.uv,2));const {name,positions,normals,uv,indices,texture,...material}=mesh;if(texture)material.map=assetTexture(texture);const m=new THREE.Mesh(g,new THREE.MeshPhysicalMaterial(material));m.name=name;m.castShadow=true;m.receiveShadow=true;group.add(m);}return group;});
 scenes=models.map(model=>{const scene=setupScene();scene.add(model);return scene;});busy=false;setExportDisabled(false);reflect();resize();status(`已更新 · ${result.ms} ms · 真实人体与独立服装网格`);waiters.splice(0).forEach(r=>r());}
function schedule(){reflect();if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;update();});}
function validateState(s){return validateComparison(s);}
async function start(){try{
 renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;$('#canvasHost').append(renderer.domElement);
 camera=new THREE.OrthographicCamera(-1,1,1,-1,.01,100);camera.position.set(0,.96,5);controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.96,0);controls.enablePan=false;controls.enableDamping=false;controls.minZoom=.65;controls.maxZoom=2.5;controls.minPolarAngle=.4;controls.maxPolarAngle=2.6;controls.addEventListener('change',()=>{syncAngle();render();});controls.update();
 const response=await fetch('./assets/human.json',{signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('人体资源读取失败（'+response.status+'）');data=await response.json();await withTimeout(Promise.all(['hair/short01/short01_diffuse.png','hair/ponytail01/ponytail01_diffuse.png','clothes/shoes05/shoes05_diffuse.png','eyebrows/eyebrow001/eyebrow001.png','eyes/materials/brown_eye.png','clothes/female_elegantsuit01/female_elegantsuit01_diffuse.png'].map(path=>assetTexture('./assets/system/'+path).userData.loaded)),20000,'人物外观贴图读取超过 20 秒，请重新载入。');worker=new Worker('./geometry-worker.js',{type:'module'});worker.onmessage=e=>{try{receiveGeometry(e);}catch(error){failModel(error);}};worker.onerror=e=>failModel(Error('人体计算线程失败：'+e.message));worker.onmessageerror=()=>failModel(Error('人体计算结果无法读取，请重新载入。'));worker.postMessage({type:'init',data});ready=true;await update();if(!ready)return;if(!models.length)throw Error('人体计算没有返回网格');window.somaStartup.complete();$$('#save,#reset,#copyBaseline,#compareMode,#capture,#exportGLB').forEach(b=>b.disabled=false);new ResizeObserver(resize).observe($('#canvasHost'));
 }catch(e){failModel(e);console.error(e);}}
for(const field of ['edit','fit','pose','color'])$$('[data-'+field+']').forEach(b=>b.onclick=()=>{state[field]=b.dataset[field];field==='edit'?reflect():schedule();});
$$('[data-body-example]').forEach(b=>b.onclick=()=>{state[state.edit]=bodyExample(state.sex,state[state.edit].height,b.dataset.bodyExample);schedule();});
for(const [id,k] of [['height','height'],['fat','bodyFatPercent'],['muscle','skeletalMuscleKg']])$('#'+id).oninput=e=>{state[state.edit][k]=+e.target.value;if(k==='height'&&$('#lockHeight').checked)state.A.height=state.B.height=+e.target.value;schedule();};
$('#lockHeight').onchange=e=>{if(e.target.checked){state.A.height=state.B.height=state[state.edit].height;schedule();}};
$('#sex').onchange=e=>{state=switchProfile(state,profiles,e.target.value);$('#lockHeight').checked=state.A.height===state.B.height;camera.zoom=1;camera.updateProjectionMatrix();schedule();};
$('#shoeStyle').onchange=e=>{state.shoeStyle=e.target.value;schedule();};$('#stockings').onchange=e=>{state.stockings=e.target.checked;schedule();};$('#bottom').onchange=e=>{state.bottom=e.target.value;schedule();};$('#showHair').onchange=e=>{state.hair=e.target.checked;schedule();};$('#footwear').onchange=e=>{state.footwear=e.target.checked;schedule();};$('#garment').onchange=e=>{state.garment=e.target.value;schedule();};$('#wireframe').onchange=e=>{state.wireframe=e.target.checked;schedule();};$('#bodyGhost').onchange=e=>{state.ghost=e.target.checked;schedule();};
$('#reset').onclick=$('#copyBaseline').onclick=()=>{state.B={...state.A};schedule();};$('#compareMode').onclick=()=>{state.triple=!state.triple;schedule();};
$$('[data-angle]').forEach(b=>b.onclick=()=>setAngle(+b.dataset.angle));const zoom=f=>{camera.zoom=Math.max(.65,Math.min(2.5,camera.zoom*f));camera.updateProjectionMatrix();render();};$('#zoomIn').onclick=()=>zoom(1.15);$('#zoomOut').onclick=()=>zoom(1/1.15);
$('#canvasHost').onkeydown=e=>{if(!ready)return;const dir=camera.position.clone().sub(controls.target),a=Math.atan2(dir.x,dir.z)*180/Math.PI;if(e.key==='ArrowLeft'){setAngle(a-15);e.preventDefault();}if(e.key==='ArrowRight'){setAngle(a+15);e.preventDefault();}if(e.key==='+'||e.key==='=')zoom(1.15);if(e.key==='-')zoom(1/1.15);};
$('#save').onclick=()=>{if(busy||scheduled)return;download(JSON.stringify({version:2,compositionModel:COMPOSITION_MODEL,...state,source:'MakeHuman CC0'},null,2),'SOMA-体型对照.json','application/json');status('对照参数已导出到浏览器下载目录。');};
$('#restore').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>100000)throw Error('参数文件过大（限 100 KB）');let parsed;try{parsed=JSON.parse(await f.text());}catch{throw Error('不是有效的 JSON 文件');}const restored=validateState(parsed);if(restored.sex!==state.sex)profiles[state.sex]=structuredClone(state);state={...state,...restored,triple:false};$('#lockHeight').checked=state.A.height===state.B.height;await update();if(ready)status(parsed.version===1||['soma-illustrative-v1','soma-regional-v2','soma-regional-v3'].includes(parsed.compositionModel)?'旧版数值已读取，外形采用新版分区规则。':'对照参数已恢复并重新适配。');}catch(err){status('未读取文件：'+err.message);}};
$('#exportGLB').onclick=async()=>{if(busy||scheduled)return;try{const binary=await new GLTFExporter().parseAsync(models[state.triple?['tight','regular','loose'].indexOf(state.fit):1],{binary:true});download(binary,'SOMA-模拟体型.glb','model/gltf-binary');status('已导出当前 B 的实际网格。');}catch(e){status('导出失败：'+e.message);}};
$('#capture').onclick=()=>{if(busy||scheduled)return;const old=camera.position.clone(),quaternion=camera.quaternion.clone(),w=renderer.domElement.width,h=renderer.domElement.height;const canvas=document.createElement('canvas');canvas.width=w*3;canvas.height=h+100;const ctx=canvas.getContext('2d');ctx.fillStyle='#253034';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#e4eee8';ctx.font='24px sans-serif';[0,90,180].forEach((angle,i)=>{setAngle(angle);ctx.drawImage(renderer.domElement,w*i,60);ctx.fillText(window.SomaI18n.text(['正面','侧面','背面'][i]),w*i+24,28,w-48);ctx.save();ctx.font='16px sans-serif';(state.triple?['紧身','常规','宽松']:['A 基线','B 模拟']).forEach((label,j,labels)=>ctx.fillText(window.SomaI18n.text(label),w*i+w*j/labels.length+24,52,w/labels.length-32));ctx.restore();});ctx.font='16px sans-serif';ctx.fillText(['SOMA 实际三维渲染',state.sex==='male'?'成年男性':'成年女性',POSE_LABELS[state.pose],{tight:'紧身',regular:'常规',loose:'宽松'}[state.fit],'外形模拟'].map(s=>window.SomaI18n.text(s)).join(' | '),24,h+90,canvas.width-48);camera.position.copy(old);camera.quaternion.copy(quaternion);controls.update();render();syncAngle();canvas.toBlob(b=>download(b,'SOMA-正侧背对照.png'),'image/png');status('正、侧、背实际渲染已导出。');};
$('#about').onclick=()=>$('#aboutDialog').showModal();
$$('[data-page]').forEach(b=>b.onclick=()=>{$$('[data-page]').forEach(x=>{x.classList.toggle('active',x===b);if(x===b)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});for(const id of ['studio','anatomy','learn'])$('#'+id).hidden=id!==b.dataset.page;if(b.dataset.page==='studio')resize();if(b.dataset.page==='anatomy'&&anatomy)anatomy.resize();});
function renderStructures(){const query=$('#structureSearch').value.toLowerCase();$('#structureList').replaceChildren();if(!anatomy)return;anatomy.meshes.filter(m=>m.name.toLowerCase().includes(query)).forEach((m,i)=>{const b=document.createElement('button');b.textContent=m.name||`未命名结构 ${i+1}`;if(m.name)b.setAttribute('translate','no');b.onclick=()=>selectMesh(m);$('#structureList').append(b);});}
function selectMesh(mesh){for(const m of anatomy.meshes){m.visible=true;m.material.emissive?.set(m===mesh?'#607b32':'#000000');m.material.transparent=m!==mesh;m.material.opacity=m===mesh?1:.15;}$('#anatomyStatus').textContent='已选择来源结构：'+(mesh.name||'未命名')+'。来源术语未翻译；未据此生成医学结论。';anatomy.render();}
$('#structureSearch').oninput=renderStructures;$('#showAll').onclick=()=>{if(!anatomy)return;for(const m of anatomy.meshes){m.visible=true;m.material.opacity=1;m.material.transparent=false;m.material.emissive?.set('#000000');}anatomy.render();};
$('#importAnatomy').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('#anatomyStatus').textContent='正在本地解析模型…';try{
 if(file.size>100*1024*1024)throw Error('请使用 100 MB 以下的未压缩 GLB');const bytes=await file.arrayBuffer();const view=new DataView(bytes);if(view.getUint32(0,true)!==0x46546c67)throw Error('不是 GLB 文件');
 const jsonLength=view.getUint32(12,true);const meta=JSON.parse(new TextDecoder().decode(bytes.slice(20,20+jsonLength)));if([...(meta.buffers||[]),...(meta.images||[])].some(x=>x.uri&&!x.uri.startsWith('data:')))throw Error('仅接受所有资源内嵌的 GLB，不会联网读取外部 URI');
 const gltf=await new GLTFLoader().parseAsync(bytes,'');if(anatomy){disposeGroup(anatomy.root);anatomy.renderer.dispose();anatomy.controls.dispose();$('#anatomyHost').replaceChildren();}
 const root=gltf.scene,box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());if(!size.length())throw Error('模型没有可显示的几何');root.position.sub(center);const wrapper=new THREE.Group();wrapper.add(root);wrapper.scale.setScalar(1.8/size.y);wrapper.position.y=.9;
 const scene=setupScene();scene.add(wrapper);const r=new THREE.WebGLRenderer({antialias:true,alpha:true});r.setPixelRatio(Math.min(devicePixelRatio,2));$('#anatomyHost').append(r.domElement);const c=new THREE.PerspectiveCamera(36,1,.01,100);c.position.set(0,.9,3.7);const ctrl=new OrbitControls(c,r.domElement);ctrl.target.set(0,.9,0);ctrl.update();const meshes=[];root.traverse(o=>{if(o.isMesh){o.material=new THREE.MeshStandardMaterial({color:'#c9bba9',roughness:.65});meshes.push(o);}});const draw=()=>r.render(scene,c),resize=()=>{const host=$('#anatomyHost');r.setSize(host.clientWidth,host.clientHeight);c.aspect=host.clientWidth/host.clientHeight;c.updateProjectionMatrix();draw();};anatomy={root:wrapper,renderer:r,controls:ctrl,meshes,render:draw,resize};ctrl.addEventListener('change',draw);resize();r.domElement.onclick=ev=>{const rect=r.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((ev.clientX-rect.left)/rect.width*2-1,-(ev.clientY-rect.top)/rect.height*2+1),c);const hit=ray.intersectObjects(meshes)[0];if(hit)selectMesh(hit.object);};$('#anatomyStatus').textContent=`已导入 ${meshes.length} 个真实网格。点击结构高亮；名称来自原文件。`;renderStructures();
 }catch(err){$('#anatomyStatus').textContent='导入失败：'+err.message;}e.target.value='';};
const context=document.modelContext;if(context?.registerTool){
 context.registerTool({name:'read_soma_comparison',description:'Read current local synthetic body comparison parameters and loaded state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({ready,busy,state,models:models.map(m=>m.userData)})});
 context.registerTool({name:'set_soma_comparison',description:'Set local illustrative body composition: bodyFatPercent (%) and skeletalMuscleKg (kg). Not a measurement or prediction. Legacy fat/muscle remain 15-85 morph controls; do not mix them with physical-unit inputs.',inputSchema:{type:'object',properties:{sex:{enum:['male','female']},height:{type:'number',minimum:145,maximum:200},bodyFatPercent:{type:'number',minimum:5,maximum:50},skeletalMuscleKg:{type:'number',minimum:5,maximum:80},fat:{type:'number',minimum:15,maximum:85,description:'Deprecated legacy morph weight, not percent'},muscle:{type:'number',minimum:15,maximum:85,description:'Deprecated legacy morph weight, not kg'},fit:{enum:['tight','regular','loose']},pose:{enum:POSE_IDS}},additionalProperties:false},execute:async input=>{
  if(!ready)throw Error('Model not loaded');
  if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['sex','height','bodyFatPercent','skeletalMuscleKg','fat','muscle','fit','pose'].includes(k)))throw Error('Invalid parameter');
  if(input.sex!==undefined&&!['male','female'].includes(input.sex))throw Error('未知人物类型');
  const legacy=input.fat!==undefined||input.muscle!==undefined;
  if(legacy&&(input.bodyFatPercent!==undefined||input.skeletalMuscleKg!==undefined))throw Error('不能混用旧版刻度与新单位');
  const switching=input.sex!==undefined&&input.sex!==state.sex,draft=switching?structuredClone(profiles[input.sex]||newProfile(input.sex)):state;
  const candidate={version:2,...draft,A:{...draft.A},B:{...draft.B}};
  for(const k of ['sex','fit','pose'])if(input[k]!==undefined)candidate[k]=input[k];
  for(const k of ['height','bodyFatPercent','skeletalMuscleKg'])if(input[k]!==undefined)candidate.B[k]=input[k];
  if(legacy){const morph=toMorphParams(candidate.sex,candidate.B);for(const k of ['fat','muscle'])if(input[k]!==undefined)morph[k]=input[k];const converted=fromLegacyParams(candidate.sex,morph);if(input.fat!==undefined)candidate.B.bodyFatPercent=converted.bodyFatPercent;if(input.muscle!==undefined)candidate.B.skeletalMuscleKg=converted.skeletalMuscleKg;}
  const valid=validateState(candidate);if(switching)profiles[state.sex]=structuredClone(state);state={...state,...valid};
  if(input.height!==undefined&&$('#lockHeight').checked)state.A.height=state.B.height;
  await update();if(!ready)throw Error('人体计算失败，请重新载入');return{ready,state,compositionModel:COMPOSITION_MODEL,notice:compositionHint(state.sex,state.B)};
 }});
}
start();
